version: '4.6.13'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
      - 7000:7000
    depends_on:
      - postgres
    restart: always
    networks:
      - stackoverflow
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - stackoverflow
      
volumes:
  pgdata:
networks:
  stackoverflow: